export { default as LoginForm } from './LoginForm'
export { default as ProfileForm } from './ProfileForm'
export { default as ProductForm } from './ProductForm'
export { default as ProductFormEdit } from './ProductFormEdit'
export { default as MainPageAdsForm } from './MainPageAdsForm'
export { default as ArticleForm } from './ArticleForm'
// export { default as DesignForm } from './DesignForm'
export { default as UserForm } from './UserForm'
export { default as RoleForm } from './RoleForm'
export { default as VerifyCodeForm } from './VerifyCodeForm'
export { default as LoginUserForm } from './LoginUserForm'
